import io
from typing import List, Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
    HRFlowable,
)

from services.report_engine.models.report_schema import ReportSchema


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and draw total page numbers,
    running headers, and footers.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_header_footer(num_pages)
            super().showPage()
        super().save()

    def draw_header_footer(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))

        # Running Header (pages 2+)
        if self._pageNumber > 1:
            self.drawString(36, 756, "SHADOW Cyber Threat Analysis Report")
            self.drawRightString(576, 756, "CONFIDENTIAL // SOC INVESTIGATION")
            self.setStrokeColor(colors.HexColor("#cbd5e1"))
            self.setLineWidth(0.5)
            self.line(36, 748, 576, 748)

        # Running Footer (all pages)
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.5)
        self.line(36, 42, 576, 42)
        self.drawString(36, 28, "Generated by SHADOW Report Engine v1.0")
        self.drawRightString(576, 28, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


class PDFRenderer:
    """
    ⭐ Enterprise PDF Renderer for SHADOW Report Engine.

    Converts a ReportSchema object into a professional, multi-page SOC PDF document
    using ReportLab.
    """

    def render(self, report: ReportSchema) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=54,
            bottomMargin=54,
        )

        styles = getSampleStyleSheet()

        # --------------------------------------------------
        # Custom Typography & Palette
        # --------------------------------------------------
        c_navy = colors.HexColor("#0f172a")
        c_blue = colors.HexColor("#1e3a8a")
        c_gray_bg = colors.HexColor("#f8fafc")
        c_border = colors.HexColor("#cbd5e1")
        c_text = colors.HexColor("#1e293b")
        c_muted = colors.HexColor("#475569")

        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=20,
            leading=24,
            textColor=c_navy,
            alignment=0,
            spaceAfter=6,
        )

        h1_style = ParagraphStyle(
            "Heading1_Custom",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            textColor=c_blue,
            spaceBefore=14,
            spaceAfter=6,
            keepWithNext=True,
        )

        h2_style = ParagraphStyle(
            "Heading2_Custom",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=10,
            leading=13,
            textColor=c_navy,
            spaceBefore=8,
            spaceAfter=4,
            keepWithNext=True,
        )

        body_style = ParagraphStyle(
            "Body_Custom",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=13,
            textColor=c_text,
            spaceAfter=4,
        )

        bullet_style = ParagraphStyle(
            "Bullet_Custom",
            parent=body_style,
            leftIndent=12,
            bulletIndent=4,
            spaceAfter=2,
        )

        table_header_style = ParagraphStyle(
            "TableHeader",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=11,
            textColor=colors.white,
        )

        table_cell_style = ParagraphStyle(
            "TableCell",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=11,
            textColor=c_text,
            wordWrap="CJK",
        )

        table_cell_bold = ParagraphStyle(
            "TableCellBold",
            parent=table_cell_style,
            fontName="Helvetica-Bold",
            textColor=c_navy,
        )

        story = []

        # --------------------------------------------------
        # 1. Document Title & Header Block
        # --------------------------------------------------
        story.append(Paragraph("SHADOW Cyber Threat Analysis Report", title_style))
        story.append(
            Paragraph(
                f"<b>Target:</b> {report.metadata.target_identifier} &nbsp;|&nbsp; <b>Type:</b> {report.metadata.target_type.upper() if report.metadata.target_type else 'N/A'}",
                body_style,
            )
        )
        story.append(Spacer(1, 4))

        meta_table_data = [
            [
                Paragraph("<b>Report ID:</b>", body_style),
                Paragraph(report.metadata.report_id, body_style),
                Paragraph("<b>Generated Time:</b>", body_style),
                Paragraph(report.metadata.generated_at, body_style),
            ],
            [
                Paragraph("<b>Target Type:</b>", body_style),
                Paragraph(str(report.metadata.target_type or "N/A").upper(), body_style),
                Paragraph("<b>Engine Version:</b>", body_style),
                Paragraph(report.metadata.version, body_style),
            ],
        ]
        meta_table = Table(meta_table_data, colWidths=[90, 180, 90, 180])
        meta_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), c_gray_bg),
                ("BOX", (0, 0), (-1, -1), 0.5, c_border),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#f1f5f9")),
                ("PADDING", (0, 0), (-1, -1), 4),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ])
        )
        story.append(meta_table)
        story.append(Spacer(1, 10))

        # --------------------------------------------------
        # 2. Executive Summary
        # --------------------------------------------------
        if report.executive_summary:
            story.append(Paragraph("1. Executive Summary", h1_style))
            story.append(HRFlowable(width="100%", thickness=1, color=c_blue, spaceBefore=1, spaceAfter=6))

            if report.executive_summary.summary_text:
                story.append(Paragraph(report.executive_summary.summary_text, body_style))
                story.append(Spacer(1, 4))

            if report.executive_summary.key_findings:
                story.append(Paragraph("<b>Key Findings:</b>", h2_style))
                for finding in report.executive_summary.key_findings:
                    story.append(Paragraph(f"• {finding}", bullet_style))
                story.append(Spacer(1, 8))

        # --------------------------------------------------
        # 3. 5W1H Investigation Framework
        # --------------------------------------------------
        if report.fivew1h:
            story.append(Paragraph("2. 5W1H Investigation Framework", h1_style))
            story.append(HRFlowable(width="100%", thickness=1, color=c_blue, spaceBefore=1, spaceAfter=6))

            five_blocks = [
                ("WHO (Target / Entity)", report.fivew1h.who),
                ("WHAT (Artifact / Category)", report.fivew1h.what),
                ("WHERE (Location / Endpoint)", report.fivew1h.where),
                ("WHEN (Timestamps)", report.fivew1h.when),
                ("WHY (Severity & Risk)", report.fivew1h.why),
                ("HOW (Behaviors & Vectors)", report.fivew1h.how),
            ]

            fw_data = []
            for label, d_dict in five_blocks:
                if not d_dict:
                    continue
                k_v_pairs = []
                for k, v in d_dict.items():
                    if isinstance(v, list):
                        v_str = ", ".join(str(item) for item in v)
                    elif isinstance(v, dict):
                        v_str = ", ".join(f"{dk}: {dv}" for dk, dv in v.items())
                    else:
                        v_str = str(v)
                    k_v_pairs.append(f"<b>{k}:</b> {v_str}")
                formatted_pairs = "<br/>".join(k_v_pairs)
                fw_data.append([
                    Paragraph(f"<b>{label}</b>", table_cell_bold),
                    Paragraph(formatted_pairs if formatted_pairs else "N/A", table_cell_style)
                ])

            if fw_data:
                fw_table = Table(fw_data, colWidths=[150, 390])
                fw_table.setStyle(
                    TableStyle([
                        ("BACKGROUND", (0, 0), (0, -1), c_gray_bg),
                        ("BOX", (0, 0), (-1, -1), 0.5, c_border),
                        ("INNERGRID", (0, 0), (-1, -1), 0.5, c_border),
                        ("PADDING", (0, 0), (-1, -1), 5),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ])
                )
                story.append(fw_table)
                story.append(Spacer(1, 10))

        # --------------------------------------------------
        # 4. Indicators of Compromise (IOC Summary)
        # --------------------------------------------------
        if report.ioc_summary and report.ioc_summary.iocs:
            story.append(Paragraph("3. Indicators of Compromise (IOC Summary)", h1_style))
            story.append(HRFlowable(width="100%", thickness=1, color=c_blue, spaceBefore=1, spaceAfter=6))

            ioc_table_data = [[
                Paragraph("IOC Type", table_header_style),
                Paragraph("Indicator Value", table_header_style),
                Paragraph("Source Origin", table_header_style)
            ]]

            for item in report.ioc_summary.iocs:
                ioc_type = item.get("type", "N/A")
                ioc_val = item.get("value", "N/A")
                ioc_src = item.get("source", "Unknown")

                ioc_table_data.append([
                    Paragraph(ioc_type, table_cell_bold),
                    Paragraph(ioc_val, table_cell_style),
                    Paragraph(ioc_src, table_cell_style)
                ])

            ioc_table = Table(ioc_table_data, colWidths=[100, 310, 130])
            ioc_table.setStyle(
                TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), c_navy),
                    ("BOX", (0, 0), (-1, -1), 0.5, c_border),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, c_border),
                    ("PADDING", (0, 0), (-1, -1), 4),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, c_gray_bg]),
                ])
            )
            story.append(ioc_table)
            story.append(Spacer(1, 10))

        # --------------------------------------------------
        # 5. Investigation Timeline
        # --------------------------------------------------
        if report.timeline and report.timeline.events:
            story.append(Paragraph("4. Investigation Timeline", h1_style))
            story.append(HRFlowable(width="100%", thickness=1, color=c_blue, spaceBefore=1, spaceAfter=6))

            timeline_table_data = [[
                Paragraph("Step", table_header_style),
                Paragraph("Title & Timestamp", table_header_style),
                Paragraph("Description", table_header_style)
            ]]

            for evt in report.timeline.events:
                step_str = f"Step {evt.get('step', '-')}"
                t_title = evt.get("title", "")
                t_stamp = evt.get("timestamp", "")
                title_ts_p = f"<b>{t_title}</b><br/><font color='#64748b' size=7.5>{t_stamp}</font>"
                desc_p = evt.get("description", "")

                timeline_table_data.append([
                    Paragraph(step_str, table_cell_bold),
                    Paragraph(title_ts_p, table_cell_style),
                    Paragraph(desc_p, table_cell_style)
                ])

            timeline_table = Table(timeline_table_data, colWidths=[50, 180, 310])
            timeline_table.setStyle(
                TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), c_navy),
                    ("BOX", (0, 0), (-1, -1), 0.5, c_border),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, c_border),
                    ("PADDING", (0, 0), (-1, -1), 4),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, c_gray_bg]),
                ])
            )
            story.append(timeline_table)
            story.append(Spacer(1, 10))

        # --------------------------------------------------
        # 6. Technical Summary
        # --------------------------------------------------
        if report.technical_summary and report.technical_summary.details:
            story.append(Paragraph("5. Technical Summary", h1_style))
            story.append(HRFlowable(width="100%", thickness=1, color=c_blue, spaceBefore=1, spaceAfter=6))

            section_idx = 1
            for sec_name, sec_dict in report.technical_summary.details.items():
                if not isinstance(sec_dict, dict) or not sec_dict:
                    continue

                story.append(Paragraph(f"5.{section_idx} {sec_name}", h2_style))

                sec_table_data = []
                for k, v in sec_dict.items():
                    sec_table_data.append([
                        Paragraph(f"<b>{k}</b>", table_cell_bold),
                        Paragraph(str(v), table_cell_style)
                    ])

                sec_table = Table(sec_table_data, colWidths=[170, 370])
                sec_table.setStyle(
                    TableStyle([
                        ("BACKGROUND", (0, 0), (0, -1), c_gray_bg),
                        ("BOX", (0, 0), (-1, -1), 0.5, c_border),
                        ("INNERGRID", (0, 0), (-1, -1), 0.5, c_border),
                        ("PADDING", (0, 0), (-1, -1), 4),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ])
                )
                story.append(sec_table)
                story.append(Spacer(1, 6))
                section_idx += 1

        # Build Document
        doc.build(story, canvasmaker=NumberedCanvas)
        buffer.seek(0)
        return buffer.getvalue()
